package me.canable.swaplocations;

import me.canable.swaplocations.Commands.SwapCMD;
import me.canable.swaplocations.Listeners.DamageEvent;
import me.canable.swaplocations.Listeners.EntitySpawn;
import me.canable.swaplocations.Listeners.TeleportEvent;
import me.canable.swaplocations.TabCompleters.SwapCompleter;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.plugin.java.JavaPlugin;

import java.util.ArrayList;
import java.util.List;

public final class Main extends JavaPlugin {
    public List<String> createList(){
        List<String> Sounds = new ArrayList<>();
        Sounds.add("AMBIENCE_CAVE");
        Sounds.add("AMBIENCE_RAIN");
        Sounds.add("AMBIENCE_THUNDER");
        Sounds.add("ANVIL_BREAK");
        Sounds.add("ANVIL_LAND");
        Sounds.add("ANVIL_USE");
        Sounds.add("ARROW_HIT");
        Sounds.add("BAT_DEATH");
        Sounds.add("BAT_HURT");
        Sounds.add("BAT_IDLE");
        Sounds.add("BAT_LOOP");
        Sounds.add("BAT_TAKEOFF");
        Sounds.add("BLAZE_BREATH");
        Sounds.add("BLAZE_DEATH");
        Sounds.add("BLAZE_HIT");
        Sounds.add("BURP");
        Sounds.add("CAT_HISS");
        Sounds.add("CAT_HIT");
        Sounds.add("CAT_MEOW");
        Sounds.add("CAT_PURR");
        Sounds.add("CAT_PURREOW");
        Sounds.add("CHEST_CLOSE");
        Sounds.add("CHEST_OPEN");
        Sounds.add("CHICKEN_EGG_POP");
        Sounds.add("CHICKEN_HURT");
        Sounds.add("CHICKEN_IDLE");
        Sounds.add("CHICKEN_WALK");
        Sounds.add("CLICK");
        Sounds.add("COW_HURT");
        Sounds.add("COW_IDLE");
        Sounds.add("COW_WALK");
        Sounds.add("CREEPER_DEATH");
        Sounds.add("CREEPER_HISS");
        Sounds.add("DIG_GRASS");
        Sounds.add("DIG_GRAVEL");
        Sounds.add("DIG_SAND");
        Sounds.add("DIG_SNOW");
        Sounds.add("DIG_STONE");
        Sounds.add("DIG_WOOD");
        Sounds.add("DIG_WOOL");
        Sounds.add("DONKEY_ANGRY");
        Sounds.add("DONKEY_DEATH");
        Sounds.add("DONKEY_HIT");
        Sounds.add("DONKEY_IDLE");
        Sounds.add("DOOR_CLOSE");
        Sounds.add("DOOR_OPEN");
        Sounds.add("DRINK");
        Sounds.add("EAT");
        Sounds.add("ENDERDRAGON_DEATH");
        Sounds.add("ENDERDRAGON_GROWL");
        Sounds.add("ENDERDRAGON_HIT");
        Sounds.add("ENDERDRAGON_WINGS");
        Sounds.add("ENDERMAN_DEATH");
        Sounds.add("ENDERMAN_HIT");
        Sounds.add("ENDERMAN_IDLE");
        Sounds.add("ENDERMAN_SCREAM");
        Sounds.add("ENDERMAN_STARE");
        Sounds.add("ENDERMAN_TELEPORT");
        Sounds.add("EXPLODE");
        Sounds.add("FALL_BIG");
        Sounds.add("FALL_SMALL");
        Sounds.add("FIRE");
        Sounds.add("FIRE_IGNITE");
        Sounds.add("FIREWORK_BLAST");
        Sounds.add("FIREWORK_BLAST2");
        Sounds.add("FIREWORK_LARGE_BLAST");
        Sounds.add("FIREWORK_LARGE_BLAST2");
        Sounds.add("FIREWORK_LAUNCH");
        Sounds.add("FIREWORK_TWINKLE");
        Sounds.add("FIREWORK_TWINKLE2");
        Sounds.add("FIZZ");
        Sounds.add("FUSE");
        Sounds.add("GHAST_CHARGE");
        Sounds.add("GHAST_DEATH");
        Sounds.add("GHAST_FIREBALL");
        Sounds.add("GHAST_MOAN");
        Sounds.add("GHAST_SCREAM");
        Sounds.add("GHAST_SCREAM2");
        Sounds.add("GLASS");
        Sounds.add("HORSE_ANGRY");
        Sounds.add("HORSE_ARMOR");
        Sounds.add("HORSE_BREATHE");
        Sounds.add("HORSE_DEATH");
        Sounds.add("HORSE_GALLOP");
        Sounds.add("HORSE_HIT");
        Sounds.add("HORSE_IDLE");
        Sounds.add("HORSE_JUMP");
        Sounds.add("HORSE_LAND");
        Sounds.add("HORSE_SADDLE");
        Sounds.add("HORSE_SKELETON_DEATH");
        Sounds.add("HORSE_SKELETON_HIT");
        Sounds.add("HORSE_SKELETON_IDLE");
        Sounds.add("HORSE_SOFT");
        Sounds.add("HORSE_WOOD");
        Sounds.add("HORSE_ZOMBIE_DEATH");
        Sounds.add("HORSE_ZOMBIE_HIT");
        Sounds.add("HORSE_ZOMBIE_IDLE");
        Sounds.add("HURT_FLESH");
        Sounds.add("IRONGOLEM_DEATH");
        Sounds.add("IRONGOLEM_HIT");
        Sounds.add("IRONGOLEM_THROW");
        Sounds.add("IRONGOLEM_WALK");
        Sounds.add("ITEM_BREAK");
        Sounds.add("ITEM_PICKUP");
        Sounds.add("LAVA");
        Sounds.add("LAVA_POP");
        Sounds.add("LEVEL_UP");
        Sounds.add("MAGMACUBE_JUMP");
        Sounds.add("MAGMACUBE_WALK");
        Sounds.add("MAGMACUBE_WALK2");
        Sounds.add("MINECART_BASE");
        Sounds.add("MINECART_INSIDE");
        Sounds.add("NOTE_BASS");
        Sounds.add("NOTE_BASS_DRUM");
        Sounds.add("NOTE_BASS_GUITAR");
        Sounds.add("NOTE_PIANO");
        Sounds.add("NOTE_PLING");
        Sounds.add("NOTE_SNARE_DRUM");
        Sounds.add("NOTE_STICKS");
        Sounds.add("ORB_PICKUP");
        Sounds.add("PIG_DEATH");
        Sounds.add("PIG_IDLE");
        Sounds.add("PIG_WALK");
        Sounds.add("PISTON_EXTEND");
        Sounds.add("PISTON_RETRACT");
        Sounds.add("PORTAL");
        Sounds.add("PORTAL_TRAVEL");
        Sounds.add("PORTAL_TRIGGER");
        Sounds.add("SHEEP_IDLE");
        Sounds.add("SHEEP_SHEAR");
        Sounds.add("SHEEP_WALK");
        Sounds.add("SHOOT_ARROW");
        Sounds.add("SILVERFISH_HIT");
        Sounds.add("SILVERFISH_IDLE");
        Sounds.add("SILVERFISH_KILL");
        Sounds.add("SILVERFISH_WALK");
        Sounds.add("SKELETON_DEATH");
        Sounds.add("SKELETON_HURT");
        Sounds.add("SKELETON_IDLE");
        Sounds.add("SKELETON_WALK");
        Sounds.add("SLIME_ATTACK");
        Sounds.add("SLIME_WALK");
        Sounds.add("SLIME_WALK2");
        Sounds.add("SPIDER_DEATH");
        Sounds.add("SPIDER_IDLE");
        Sounds.add("SPIDER_WALK");
        Sounds.add("SPLASH");
        Sounds.add("SPLASH2");
        Sounds.add("STEP_GRASS");
        Sounds.add("STEP_GRAVEL");
        Sounds.add("STEP_LADDER");
        Sounds.add("STEP_SAND");
        Sounds.add("STEP_SNOW");
        Sounds.add("STEP_STONE");
        Sounds.add("STEP_WOOD");
        Sounds.add("STEP_WOOL");
        Sounds.add("SUCCESSFUL_HIT");
        Sounds.add("SWIM");
        Sounds.add("VILLAGER_DEATH");
        Sounds.add("VILLAGER_HAGGLE");
        Sounds.add("VILLAGER_HIT");
        Sounds.add("VILLAGER_IDLE");
        Sounds.add("VILLAGER_NO");
        Sounds.add("VILLAGER_YES");
        Sounds.add("WATER");
        Sounds.add("WITHER_DEATH");
        Sounds.add("WITHER_HURT");
        Sounds.add("WITHER_IDLE");
        Sounds.add("WITHER_SHOOT");
        Sounds.add("WITHER_SPAWN");
        Sounds.add("WOLF_BARK");
        Sounds.add("WOLF_DEATH");
        Sounds.add("WOLF_GROWL");
        Sounds.add("WOLF_HOWL");
        Sounds.add("WOLF_HURT");
        Sounds.add("WOLF_PANT");
        Sounds.add("WOLF_SHAKE");
        Sounds.add("WOLF_WALK");
        Sounds.add("WOLF_WHINE");
        Sounds.add("WOOD_CLICK");
        Sounds.add("ZOMBIE_DEATH");
        Sounds.add("ZOMBIE_HURT");
        Sounds.add("ZOMBIE_IDLE");
        Sounds.add("ZOMBIE_INFECT");
        Sounds.add("ZOMBIE_METAL");
        Sounds.add("ZOMBIE_PIG_ANGRY");
        Sounds.add("ZOMBIE_PIG_DEATH");
        Sounds.add("ZOMBIE_PIG_HURT");
        Sounds.add("ZOMBIE_PIG_IDLE");
        Sounds.add("ZOMBIE_REMEDY");
        Sounds.add("ZOMBIE_UNFECT");
        Sounds.add("ZOMBIE_WALK");
        Sounds.add("ZOMBIE_WOOD");
        Sounds.add("ZOMBIE_WOODBREAK");
        return Sounds;
    }
    @Override
    public void onEnable() {
        getCommand("swaplocations").setExecutor(new SwapCMD(this));
        getCommand("swaplocations").setTabCompleter(new SwapCompleter(this));
        FileConfiguration cfg = this.getConfig();
        if(!cfg.contains("Enabled")){
            cfg.set("Enabled", "true");
            this.saveConfig();
        }
        if(!cfg.contains("Type")){
            cfg.set("Type", "EGG");
            this.saveConfig();
        }
        if(!cfg.contains("Prefix")){
            cfg.set("Prefix", "§b§lSwapLocations §8» §r");
            this.saveConfig();
        }
        if(!cfg.contains("Sound")){
            cfg.set("Sound", "ENDERMAN_TELEPORT");
            this.saveConfig();
        }
        getServer().getPluginManager().registerEvents(new DamageEvent(this),this);
        getServer().getPluginManager().registerEvents(new TeleportEvent(this),this);
        getServer().getPluginManager().registerEvents(new EntitySpawn(this),this);
        this.saveConfig();
    }
}
